sudo: required
services:
  - docker

before_install:
  - docker build -t paulgoertzen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paulgoertzen/react-test npm test -- --coverage

after_success:
  - docker build -t paulgoertzen/multi-client ./client
  - docker build -t paulgoertzen/multi-worker ./worker
  - docker build -t paulgoertzen/multi-nginx ./nginx
  - docker build -t paulgoertzen/multi-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push paulgoertzen/multi-client
  - docker push paulgoertzen/multi-server
  - docker push paulgoertzen/multi-nginx
  - docker push paulgoertzen/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: Multi-Docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-076057130695
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY